.TH "building_t" 3 "Mon May 6 2019" "Monster Adventure Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
building_t \- Building Generation Module
.PP
Holds building origin, dimensions, and door location\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game_building\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBx\fP"
.br
.ti -1c
.RI "char \fBy\fP"
.br
.ti -1c
.RI "char \fBmax_x\fP"
.br
.ti -1c
.RI "char \fBmax_y\fP"
.br
.ti -1c
.RI "char \fBdx\fP"
.br
.ti -1c
.RI "char \fBdy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Building Generation Module
.PP
Holds building origin, dimensions, and door location\&. 


.PP
\fBWarning:\fP
.RS 4
This code is assumed to be located in game\&.h for this version of the game and is included for documentation purposes as a separate file 
.PP
Y values start from the top\&. Make max_y the larger value but recall that it will be the 'bottom' Building Info Struct 
.RE
.PP

.PP
Definition at line 25 of file game_building\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char dx"

.PP
Definition at line 30 of file game_building\&.h\&.
.SS "char dy"

.PP
Definition at line 31 of file game_building\&.h\&.
.SS "char max_x"

.PP
Definition at line 28 of file game_building\&.h\&.
.SS "char max_y"

.PP
Definition at line 29 of file game_building\&.h\&.
.SS "char x"

.PP
Definition at line 26 of file game_building\&.h\&.
.SS "char y"

.PP
Definition at line 27 of file game_building\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Monster Adventure Game from the source code\&.
