.TH "enemy_t" 3 "Mon May 6 2019" "Monster Adventure Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enemy_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monster\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBhealth\fP"
.br
.ti -1c
.RI "int \fBdam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enemy Structure 

.SH "Author"
.PP 
Generated automatically by Doxygen for Monster Adventure Game from the source code\&.
