.TH "main.c" 3 "Mon May 6 2019" "Monster Adventure Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c
.SH SYNOPSIS
.br
.PP
\fC#include <msp430\&.h>\fP
.br
\fC#include 'project_settings\&.h'\fP
.br
\fC#include 'monster\&.h'\fP
.br
\fC#include 'subsystem\&.h'\fP
.br
\fC#include 'task\&.h'\fP
.br
\fC#include 'uart\&.h'\fP
.br
\fC#include 'hal_general\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.ti -1c
.RI "void \fBSetClk24MHz\fP ()"
.br
.ti -1c
.RI "void \fBSetVcoreUp\fP (unsigned int level)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 9 of file main\&.c\&.
.SS "void SetClk24MHz ()"

.PP
Definition at line 34 of file main\&.c\&.
.SS "void SetVcoreUp (unsigned int level)"

.PP
Definition at line 83 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Monster Adventure Game from the source code\&.
