.TH "monster_game_t" 3 "Mon May 6 2019" "Monster Adventure Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
monster_game_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monster\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structs to support game objectsGame Structure 
.PP
Definition at line 75 of file monster\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t id"

.PP
Definition at line 76 of file monster\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Monster Adventure Game from the source code\&.
