.TH "monster.h" 3 "Mon May 6 2019" "Monster Adventure Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
monster.h
.SH SYNOPSIS
.br
.PP
\fC#include 'project_settings\&.h'\fP
.br
\fC#include 'random_int\&.h'\fP
.br
\fC#include 'stddef\&.h'\fP
.br
\fC#include 'strings\&.h'\fP
.br
\fC#include 'game\&.h'\fP
.br
\fC#include 'timing\&.h'\fP
.br
\fC#include 'task\&.h'\fP
.br
\fC#include 'terminal\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmonster_game_t\fP"
.br
.ti -1c
.RI "struct \fBitem_t\fP"
.br
.ti -1c
.RI "struct \fBenemy_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBitem_t\fP \fBitem_t\fP"
.br
.ti -1c
.RI "typedef struct \fBenemy_t\fP \fBenemy_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmonsterGame_init\fP (void)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Monster Adventure Game from the source code\&.
