.TH "project_settings.h" 3 "Mon May 6 2019" "Monster Adventure Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
project_settings.h
.SH SYNOPSIS
.br
.PP
\fC#include 'library\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFCPU\fP   24000000"
.br
.ti -1c
.RI "#define \fBUSE_MODULE_TASK\fP"
.br
.ti -1c
.RI "#define \fBUSE_MODULE_SUBSYSTEM\fP"
.br
.ti -1c
.RI "#define \fBUSE_MODULE_BUFFER_PRINTF\fP"
.br
.ti -1c
.RI "#define \fBSUBSYSTEM_UART\fP   UART0"
.br
.ti -1c
.RI "#define \fBUART0_TX_BUFFER_LENGTH\fP   2048"
.br
.ti -1c
.RI "#define \fBUSE_UART0\fP"
.br
.ti -1c
.RI "#define \fBTASK_MAX_LENGTH\fP   100"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FCPU   24000000"

.PP
Definition at line 11 of file project_settings\&.h\&.
.SS "#define SUBSYSTEM_UART   UART0"

.PP
Definition at line 21 of file project_settings\&.h\&.
.SS "#define TASK_MAX_LENGTH   100"

.PP
Definition at line 27 of file project_settings\&.h\&.
.SS "#define UART0_TX_BUFFER_LENGTH   2048"

.PP
Definition at line 23 of file project_settings\&.h\&.
.SS "#define USE_MODULE_BUFFER_PRINTF"

.PP
Definition at line 19 of file project_settings\&.h\&.
.SS "#define USE_MODULE_SUBSYSTEM"

.PP
Definition at line 18 of file project_settings\&.h\&.
.SS "#define USE_MODULE_TASK"

.PP
Definition at line 17 of file project_settings\&.h\&.
.SS "#define USE_UART0"

.PP
Definition at line 25 of file project_settings\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Monster Adventure Game from the source code\&.
