.TH "enemy_t" 3 "Sun May 5 2019" "ScrumShank Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enemy_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monster\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBhealth\fP"
.br
.ti -1c
.RI "int \fBdam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enemy Structure 
.SH "Field Documentation"
.PP 
.SS "int dam"

.SS "int health"


.SH "Author"
.PP 
Generated automatically by Doxygen for ScrumShank Final Project from the source code\&.
