.TH "item_t" 3 "Sun May 5 2019" "ScrumShank Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
item_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monster\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBx\fP"
.br
.ti -1c
.RI "char \fBy\fP"
.br
.ti -1c
.RI "char \fBstatus\fP"
.br
.ti -1c
.RI "char \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Item Structure 
.SH "Field Documentation"
.PP 
.SS "char c"

.SS "char status"

.SS "char x"

.SS "char y"


.SH "Author"
.PP 
Generated automatically by Doxygen for ScrumShank Final Project from the source code\&.
