.TH "monster_game_t" 3 "Sun May 5 2019" "ScrumShank Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
monster_game_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monster\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structs to support game objectsGame Structure 
.SH "Field Documentation"
.PP 
.SS "uint8_t id"


.SH "Author"
.PP 
Generated automatically by Doxygen for ScrumShank Final Project from the source code\&.
