.TH "printf.c" 3 "Sun May 5 2019" "ScrumShank Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
printf.c
.SH SYNOPSIS
.br
.PP
\fC#include <msp430\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.ti -1c
.RI "void \fBmyprintf\fP (volatile char string[], int length)"
.br
.ti -1c
.RI "__interrupt void \fBUSCI_A1_ISR\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile unsigned int \fBi\fP"
.br
.ti -1c
.RI "volatile size_t \fBsizeString\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SS "void myprintf (volatile char string[], int length)"

.SS "__interrupt void USCI_A1_ISR (void)"

.SH "Variable Documentation"
.PP 
.SS "volatile unsigned int i"

.SS "volatile size_t sizeString"

.SH "Author"
.PP 
Generated automatically by Doxygen for ScrumShank Final Project from the source code\&.
